### ISSUE TITLE
Naive install fails

### ISSUE THREAD

**Issue by richelbilderbeek** [JohanvandeKoppel/clMussels#1]
A naive installation fails (i.e. an installation following README.md):

Fresh clone:

```
richel@richel-K73E:~/GitHubs/johanvandekoppel$ git clone https://github.com/JohanvandeKoppel/clMussels.git
Cloning into 'clMussels'...
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 29 (delta 10), reused 12 (delta 3)
Unpacking objects: 100% (29/29), done.
Checking connectivity... done.
```

Go into the folder:

```
richel@richel-K73E:~/GitHubs/johanvandekoppel$ cd clMussels/
```

Try as in the readme, yet this fails:

```
richel@richel-K73E:~/GitHubs/johanvandekoppel/clMussels$ cmake ..
CMake Error: The source directory "/home/richel/GitHubs/johanvandekoppel" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

So, which files are present?

```
richel@richel-K73E:~/GitHubs/johanvandekoppel/clMussels$ ls
CMakeLists.txt  Computing_Kernel.cl  Device_Utilities.cpp  Device_Utilities.h  LICENSE  Main_Program.cpp  PlotMussels.m  PlotMussels.r  README.md  Settings_and_Parameters.h
```

I am not sure what causes this error. Is there a file missing or is the README.md incorrect.

**Comment by JohanvandeKoppel** [comment]
En leuk dat je het probeert! Wouw!

Je hebt helemaal gelijk! Je moet eerst een "build" directory maken, daar in gaan, en dan cmake.. doen.

Johan
---------
Johan van de Koppel
Senior researcher, Spatial Ecology Department, NIOZ-Yerseke
Honorary Professor, University of Groningen

Royal Netherlands Institute for Sea Research - Location Yerseke
P.O. Box 140, 4400AC Yerseke, The Netherlands
Phone: 31 (0)113 577455
Homepage: johanvandekoppel.nl<http://johanvandekoppel.nl/>

**Comment by JohanvandeKoppel** [comment]
Thanks a lot for trying this! My documentation is incomplete. 

Install the code
Make a subdirectory called "build" : mkdir build
go into that directory: cd build.
Do as specified!

**Comment by richelbilderbeek** [comment]
I saw that these instructions now moved to the General-Instructions GitHub. IMHO it is great the documentation is improved, yet I'd prefer a GitHub to be complete, e.g. add an install script to this GitHub, that downloads and installs the General-Instructions GitHub. But hey, that's just me. Keep up the good work!

BTW, IMHO you can close this issue now.

**Comment by richelbilderbeek** [comment]
I'll suggest a build script somewhere in the future by a Pull Request (you'll see).
